require 'bundler/setup'
require 'nanoc3/tasks'

task :deploy do
  system "nanoc compile"

  Dir.chdir("..") do
    system "mv website/output/* ."
    system "rm -r website/output"
    system "git add ."
    system "git commit -m \"Deploying on #{Date.today}\""
    system "git push origin gh-pages"
  end
end
